version: '3'
name: 'backend-nodejs'
services:
  db:
    container_name: postgres
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: on-failure
