version: '3'
name: 'backend-express'
services:
  api:
    container_name: api
    image: angelozdev/api:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      NODE_ENV: development
  db:
    container_name: postgres
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: on-failure
