### GET a user by id
GET http://localhost:3000/api/v1/users/12

### POST a new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "email": "josshn@email.com",
  "password": "password"
}

### UPDATE an user
PATCH http://localhost:3000/api/v1/users/12
Content-Type: application/json

{
  "currentPassword": "Admin.1234"
}