### Get all products from the database
GET http://localhost:3000/api/v1/products

### Get a single product with limit and offset
GET http://localhost:3000/api/v1/products?limit=5&offset=10

### Get a single product from the database
GET http://localhost:3000/api/v1/products/10

### Create a new product
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Product 1 description",
  "price": "12.4",
  "image": "https://example.com/image.jpg"
}

### Update a product
PATCH http://localhost:3000/api/v1/products/12
Content-Type: application/json

{
  "name": "Product 1 updated :D",
  "description": "Product 1 modified"
}

### Delete a product
DELETE http://localhost:3000/api/v1/products/12
